esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

api:
  encryption:
    key: ${api_key}

web_server:
  port: 80

logger:

ota:
  platform: esphome

captive_portal:

sensor: 
  - platform: uptime
    name: Uptime

  - platform: adc
    pin: VCC
    name: VCC Voltage


binary_sensor:
  - platform: status
    name: "Home Assistant Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    dns_address:
      name: ESP DNS Address